services:
  - type: web
    name: law-school-study-ws
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    pythonVersion: 3.9.12

  - name: law-school-study-worker
    type: worker
    env: python
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    
    pythonVersion: 3.9.12