services:
  - type: web
    name: law-school-study-ws
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    pythonVersion: 3.9.12

  - name: law-school-study-worker
    type: worker
    env: python
    runtime: python3
    buildCommand: "apt-get install -y libgl1-mesa-glx libglib2.0-0 && pip install -r requirements-worker.txt"
    startCommand: "celery -A tasks.celery_app worker --loglevel=info --concurrency=2"
    pythonVersion: 3.9.12