# utils/document_loaders/docling_loader.py

"""
Docling-backed PDF loader for hierarchical RAG ingest.

Replaces the PyMuPDF/OCR loader path when USE_HIERARCHICAL_INGEST=true.
Uses Docling's DocumentConverter + HybridChunker to produce semantically
structured chunks with:
  - chunk_type  : prose | table | heading | list | citation_block
  - section_path: hierarchical heading breadcrumb ("I. Background > A. Facts")
  - table_data  : structured rows/cols for table chunks
  - page_number : from Docling provenance
  - parent_chunk_id: self-FK skeleton (populated post-insert by build_section_summaries)

Tables get special treatment per the "retrieved" spec:
  - content  = Markdown rendering (stored in DB)
  - embed_text = LLM-written summary (generated by _generate_chunk_blurbs_async, NOT here)
  - metadata.table  = {"headers": [...], "rows": [[...], ...]}
  - metadata.caption = first caption string, if present
"""

import io
import logging
import os
import threading
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, Iterator, List, Optional, Tuple

from .base import BaseDocumentLoader

logger = logging.getLogger(__name__)

# Maximum table dimensions to render inline vs. summarise-only at generation time.
# Stored in metadata so the generation layer can apply the rule without re-querying.
TABLE_INLINE_MAX_ROWS = 30
TABLE_INLINE_MAX_COLS = 8

# TableFormer runs over every page when enabled and is a large share of parse
# time.  Court opinions and statutes — the dominant input here — contain almost
# no tables, so this is worth turning off once measured.  Default stays on to
# preserve existing behaviour.
DOCLING_TABLE_STRUCTURE = os.getenv("DOCLING_TABLE_STRUCTURE", "true").lower() == "true"

# Threads Docling's own pipeline may use. Defaults to the box's CPU count.
DOCLING_NUM_THREADS = int(os.getenv("DOCLING_NUM_THREADS", str(os.cpu_count() or 2)))

# How many documents may be inside converter.convert() at the same time.
# Each concurrent conversion holds its own page rasters and intermediate layout
# tensors, so this is the main lever on peak worker memory. Default 1 — raise it
# only after watching RSS on a real batch.
DOCLING_PARSE_CONCURRENCY = max(1, int(os.getenv("DOCLING_PARSE_CONCURRENCY", "1")))
_PARSE_SLOTS = threading.BoundedSemaphore(DOCLING_PARSE_CONCURRENCY)


def _build_minimal_pdf() -> bytes:
    """
    A valid one-page PDF with a single line of text, used only to warm Docling's
    pipeline at worker start. Built rather than hard-coded so the xref offsets
    are always correct.
    """
    content = b"BT /F1 12 Tf 20 100 Td (warmup) Tj ET\n"
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length %d >>\nstream\n" % len(content) + content + b"endstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % i + body + b"\nendobj\n"

    xref_pos = len(out)
    out += b"xref\n0 %d\n" % (len(objects) + 1)
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += b"%010d 00000 n \n" % off
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (
        len(objects) + 1,
        xref_pos,
    )
    return bytes(out)


_MINIMAL_PDF = _build_minimal_pdf()


# ——— Data Structure ———————————————————————————————————————————————————————————


@dataclass
class DocChunk:
    """
    Structured output of DoclingPDFLoader.load_document().

    The fields map 1-to-1 onto the new document_vector_store columns so that
    _embed_batch_async can insert them without further transformation.
    """
    chunk_id: str
    content: str                          # text stored in DB (markdown for tables)
    embed_text: str                       # text actually embedded (set after blurb gen)
    chunk_type: str                       # prose|table|heading|list|citation_block
    section_path: str                     # "Ch.1 > §A" breadcrumb
    page_number: Optional[int]
    chunk_index: int
    parent_chunk_id: Optional[str] = None

    # table-only extras (populated by _extract_table_data)
    table_data: Optional[Dict[str, Any]] = None   # {"headers": [], "rows": [[]]}
    caption: Optional[str] = None
    table_headers: Optional[List[str]] = None

    # will be filled by _generate_chunk_blurbs_async before embedding
    chunk_summary: Optional[str] = None

    # extra metadata forwarded to the metadata JSON column
    extra_meta: Dict[str, Any] = field(default_factory=dict)

    def to_metadata_dict(
        self,
        source_id: str,
        source_filename: str,
        cdn_url: str,
    ) -> Dict[str, Any]:
        """Produce the dict stored in document_vector_store.metadata (JSONB)."""
        d: Dict[str, Any] = {
            "filename": source_filename,
            "title": source_filename,
            "page": self.page_number,
            "chunk_index": self.chunk_index,
            "source_id": cdn_url,
            # new hierarchical columns
            "chunk_type": self.chunk_type,
            "section_path": self.section_path,
            "chunk_summary": self.chunk_summary,
            "parent_chunk_id": self.parent_chunk_id,
        }
        if self.table_data is not None:
            d["table"] = self.table_data
        if self.caption:
            d["caption"] = self.caption
        if self.table_headers:
            d["headers"] = self.table_headers
        d.update(self.extra_meta)
        return d


# ——— Loader ——————————————————————————————————————————————————————————————————


class DoclingPDFLoader(BaseDocumentLoader):
    """
    PDF loader built on Docling DocumentConverter + HybridChunker.

    Implements the BaseDocumentLoader interface AND provides the richer
    load_document() method used by the hierarchical ingest path.

    stream_documents() is kept for interface compatibility but delegates to
    load_document() and strips the extra metadata down to (text, meta) tuples
    so the old processor.process_documents_streaming path could theoretically
    still call it (though the hierarchical path bypasses it).
    """

    name = "docling"

    def __init__(self, max_tokens: int = 512, merge_peers: bool = True):
        self.max_tokens = max_tokens
        self.merge_peers = merge_peers
        self._converter_text = None   # lazy-init, do_ocr=False (text-layer PDFs)
        self._converter_ocr  = None   # lazy-init, Tesseract CLI (scanned PDFs)
        self._chunker = None
        # Guards converter construction AND conversion — see _ensure_ready and
        # load_document. The worker runs `-P threads`, so several documents can
        # reach this object concurrently.
        self._lock = threading.RLock()

    # ——— Lazy initialisation ———————————————————————————————————————————————

    def _ensure_ready(self) -> None:
        # Double-checked locking: without the lock, N threads arriving together
        # would each see _converter_text is None and each build a full set of
        # converters, loading N copies of the layout model.
        if self._converter_text is not None:
            return

        with self._lock:
            if self._converter_text is not None:
                return
            # Logs the RSS cost of the converters. Seeing this line ONCE per
            # worker is the proof that the singleton is working; seeing it once
            # per document is the bug that caused the 4GB OOM.
            from utils.ingest_telemetry import telemetry
            with telemetry.model_load("Docling converters"):
                self._build()

    def _build(self) -> None:
        try:
            from docling.document_converter import DocumentConverter, PdfFormatOption
            from docling.datamodel.base_models import InputFormat
            from docling.datamodel.pipeline_options import (
                PdfPipelineOptions,
                TesseractCliOcrOptions,
            )
            from docling.chunking import HybridChunker
        except ImportError as exc:
            raise ImportError(
                "docling is required for hierarchical ingest. "
                "Run: pip install docling"
            ) from exc

        def _accelerate(opts):
            """Apply thread count if this docling build exposes accelerator options."""
            try:
                from docling.datamodel.pipeline_options import AcceleratorOptions

                opts.accelerator_options = AcceleratorOptions(
                    num_threads=DOCLING_NUM_THREADS
                )
            except Exception:
                # Older docling builds don't have AcceleratorOptions — harmless.
                pass
            return opts

        # ── Text-layer converter — OCR disabled, fast path ────────────────
        self._converter_text = DocumentConverter(
            format_options={
                InputFormat.PDF: PdfFormatOption(
                    pipeline_options=_accelerate(
                        PdfPipelineOptions(
                            do_ocr=False,
                            do_table_structure=DOCLING_TABLE_STRUCTURE,
                        )
                    )
                )
            }
        )

        # ── Scanned-PDF converter — Tesseract CLI OCR ─────────────────────
        # TesseractCliOcrOptions uses the system tesseract binary (already
        # installed — pytesseract is in requirements-worker.txt).
        # Does NOT download 40 MB RapidOCR models; ~2–3× faster on CPU.
        self._converter_ocr = DocumentConverter(
            format_options={
                InputFormat.PDF: PdfFormatOption(
                    pipeline_options=_accelerate(
                        PdfPipelineOptions(
                            do_ocr=True,
                            do_table_structure=DOCLING_TABLE_STRUCTURE,
                            ocr_options=TesseractCliOcrOptions(lang=["eng"]),
                        )
                    )
                )
            }
        )

        # HybridChunker: use the default tokenizer with our max_tokens cap.
        # The spec calls for a voyage-law-2–compatible tokenizer; since that
        # tokenizer is not publicly available on HuggingFace, we use the
        # HybridChunker default (character-based with ~4 chars/token estimate)
        # and set max_tokens=512 so chunks stay well within voyage's 16k window.
        # Replace tokenizer= here if a voyage-compatible HF tokenizer ships.
        self._chunker = HybridChunker(
            max_tokens=self.max_tokens,
            merge_peers=self.merge_peers,
        )
        logger.info(
            f"🔧 DoclingPDFLoader ready: text-layer + Tesseract OCR converters "
            f"(max_tokens={self.max_tokens}, merge_peers={self.merge_peers}, "
            f"table_structure={DOCLING_TABLE_STRUCTURE}, threads={DOCLING_NUM_THREADS})"
        )

    # ——— Warm-up ———————————————————————————————————————————————————————————

    def warm_up(self) -> bool:
        """
        Force the text-layer pipeline to build and load its models.

        Constructing a DocumentConverter does NOT load anything — docling builds
        the pipeline lazily on the first convert(), so calling _ensure_ready()
        alone still leaves the first real upload paying the full model-load cost
        (~30s). Running one tiny conversion here moves that cost to worker boot.

        Returns True if the warm conversion succeeded. Never raises.
        """
        try:
            self._ensure_ready()

            from docling.datamodel.document import DocumentStream

            stream = DocumentStream(
                name="warmup.pdf", stream=io.BytesIO(_MINIMAL_PDF)
            )
            self._converter_text.convert(stream)
            logger.info("🔥 Docling text-layer pipeline warmed (models resident)")
            return True
        except Exception as exc:
            logger.warning(f"⚠️ Docling warm-up conversion failed (non-fatal): {exc}")
            return False

    # ——— Public API ————————————————————————————————————————————————————————

    def load_document(
        self,
        file_buffer: io.BytesIO,
        source_id: str,
        source_filename: str,
        cdn_url: str,
    ) -> Tuple[List[str], List[Dict], "DoclingDocument"]:  # noqa: F821
        """
        Parse and chunk a PDF, returning:
          (texts, metadatas, raw_docling_doc)

        texts     — list of strings; for tables this is the Markdown rendering
        metadatas — list of metadata dicts (to_metadata_dict output)
        raw_doc   — the DoclingDocument; carry it through to extract the TOC
                    and first-N-chars sample for extract_doc_summary/concepts.

        Note: chunk_summary / embed_text are NOT populated here.
        They are filled by _generate_chunk_blurbs_async before embedding.
        """
        self._ensure_ready()

        file_buffer.seek(0)

        # ── OCR bypass: skip Tesseract for text-layer PDFs (< 100ms check) ──
        # Published legal documents (court opinions, statutes, law reviews) are
        # virtually always text-layer PDFs — running OCR wastes 10–15 minutes.
        try:
            from utils.document_loaders.loader_factory import is_pdf_text_based
            _is_text = is_pdf_text_based(file_buffer)
        except Exception:
            _is_text = False   # if the check itself fails, fall back to OCR path

        if _is_text:
            converter = self._converter_text
            logger.info(f"⚡ OCR bypassed for '{source_filename}' (text-layer detected)")
        else:
            converter = self._converter_ocr
            logger.info(f"🔍 Running Tesseract OCR for '{source_filename}' (image-based PDF)")

        file_buffer.seek(0)
        try:
            from docling.datamodel.document import DocumentStream
            from utils.ingest_telemetry import telemetry

            stream = DocumentStream(name=source_filename, stream=file_buffer)
            # Serialised deliberately. Docling's DocumentConverter holds mutable
            # pipeline state and is not documented as thread-safe, and each
            # concurrent conversion also holds its own page rasters in memory —
            # six at once is what pushed the 4GB worker over its limit.
            # DOCLING_PARSE_CONCURRENCY controls how many may overlap.
            with telemetry.parse_slot(source_id, _PARSE_SLOTS):
                result = converter.convert(stream)
        except Exception as exc:
            logger.error(f"❌ Docling conversion failed for {source_filename}: {exc}")
            raise

        doc = result.document
        raw_chunks = list(self._chunker.chunk(dl_doc=doc))
        logger.info(
            f"📄 Docling parsed '{source_filename}': "
            f"{len(raw_chunks)} raw chunks from {len(doc.pages)} pages"
        )

        doc_chunks: List[DocChunk] = []
        for idx, raw in enumerate(raw_chunks):
            dc = self._build_doc_chunk(raw, idx, doc)
            doc_chunks.append(dc)

        # Assign parent_chunk_id for small prose chunks that are children of a heading
        doc_chunks = self._assign_parent_ids(doc_chunks)

        texts = [c.content for c in doc_chunks]
        metadatas = [
            c.to_metadata_dict(source_id, source_filename, cdn_url)
            for c in doc_chunks
        ]

        logger.info(
            f"✅ DoclingPDFLoader: {len(doc_chunks)} chunks "
            f"({sum(1 for c in doc_chunks if c.chunk_type == 'table')} tables, "
            f"{sum(1 for c in doc_chunks if c.chunk_type == 'heading')} headings)"
        )
        return texts, metadatas, doc

    # ——— stream_documents (BaseDocumentLoader compatibility) ——————————————

    def stream_documents(self, source: io.BytesIO) -> Iterator[Tuple[str, Dict]]:
        """
        Yields (text, metadata) tuples — kept for interface compatibility.
        The hierarchical ingest path calls load_document() directly and never
        reaches this method.
        """
        texts, metadatas, _ = self.load_document(source, "", "document.pdf", "")
        for text, meta in zip(texts, metadatas):
            yield text, meta

    def load_documents(self, source: io.BytesIO):
        texts, metadatas, _ = self.load_document(source, "", "document.pdf", "")
        return list(zip(texts, metadatas))

    # ——— Internal helpers —————————————————————————————————————————————————

    def _build_doc_chunk(self, raw_chunk, idx: int, doc) -> DocChunk:
        """Convert a Docling HybridChunk into our DocChunk datatype."""
        try:
            from docling.datamodel.base_models import DocItemLabel
        except ImportError:
            DocItemLabel = None

        meta = raw_chunk.meta

        # ── Chunk type detection ─────────────────────────────────────────
        chunk_type = "prose"
        table_data: Optional[Dict] = None
        caption: Optional[str] = None
        table_headers: Optional[List[str]] = None

        doc_items = getattr(meta, "doc_items", []) or []
        for item in doc_items:
            label = getattr(item, "label", None)
            if label is None:
                continue
            label_str = str(label).lower()
            if "table" in label_str:
                chunk_type = "table"
                table_data, caption, table_headers = self._extract_table_data(item, doc)
                break
            elif "heading" in label_str:
                chunk_type = "heading"
            elif "list" in label_str and chunk_type == "prose":
                chunk_type = "list"

        # ── Section path from heading breadcrumb ─────────────────────────
        headings: List[str] = list(getattr(meta, "headings", []) or [])
        section_path = " > ".join(headings) if headings else ""

        # ── Page number from provenance ───────────────────────────────────
        page_number = self._get_page_number(doc_items)

        # ── Content ───────────────────────────────────────────────────────
        if chunk_type == "table" and doc_items:
            # For tables, content = Markdown rendering
            for item in doc_items:
                if "table" in str(getattr(item, "label", "")).lower():
                    try:
                        content = item.export_to_markdown()
                    except Exception:
                        content = raw_chunk.text or ""
                    break
            else:
                content = raw_chunk.text or ""
        else:
            content = raw_chunk.text or ""

        return DocChunk(
            chunk_id=str(uuid.uuid4()),
            content=content,
            embed_text=content,  # placeholder; overwritten by blurb generation
            chunk_type=chunk_type,
            section_path=section_path,
            page_number=page_number,
            chunk_index=idx,
            table_data=table_data,
            caption=caption,
            table_headers=table_headers,
        )

    @staticmethod
    def _extract_table_data(
        table_item, doc
    ) -> Tuple[Optional[Dict], Optional[str], Optional[List[str]]]:
        """
        Extract structured rows/cols from a Docling TableItem.

        Returns (table_data_dict, caption_str, headers_list).
        table_data_dict schema: {"headers": [...], "rows": [[...], ...],
                                  "num_rows": int, "num_cols": int}
        """
        table_data: Optional[Dict] = None
        caption: Optional[str] = None
        headers: Optional[List[str]] = None

        try:
            data = getattr(table_item, "data", None)
            if data is not None:
                grid = getattr(data, "grid", None)
                if grid:
                    rows = []
                    for row in grid:
                        rows.append([
                            getattr(cell, "text", "") for cell in row
                        ])

                    num_rows = len(rows)
                    num_cols = max((len(r) for r in rows), default=0)

                    # Treat first row as headers when the table has a header flag
                    # or just always treat first row as headers for legal tables.
                    if rows:
                        headers = rows[0]
                        data_rows = rows[1:]
                    else:
                        data_rows = rows

                    table_data = {
                        "headers": headers or [],
                        "rows": data_rows,
                        "num_rows": num_rows,
                        "num_cols": num_cols,
                        "inline": (
                            num_rows <= TABLE_INLINE_MAX_ROWS
                            and num_cols <= TABLE_INLINE_MAX_COLS
                        ),
                    }
        except Exception as e:
            logger.debug(f"Table data extraction failed: {e}")

        try:
            captions = getattr(table_item, "captions", None)
            if captions:
                # captions may be a list of RefItem; resolve text from doc
                first = captions[0]
                if hasattr(first, "resolve") and doc is not None:
                    caption = first.resolve(doc).text
                elif hasattr(first, "text"):
                    caption = first.text
                else:
                    caption = str(first)
        except Exception as e:
            logger.debug(f"Caption extraction failed: {e}")

        return table_data, caption, headers

    @staticmethod
    def _get_page_number(doc_items) -> Optional[int]:
        for item in doc_items:
            prov = getattr(item, "prov", None)
            if prov:
                first = prov[0] if isinstance(prov, (list, tuple)) else prov
                page_no = getattr(first, "page_no", None)
                if page_no is not None:
                    return int(page_no)
        return None

    @staticmethod
    def _assign_parent_ids(doc_chunks: List[DocChunk]) -> List[DocChunk]:
        """
        Light pass: each prose/list/citation chunk that immediately follows a
        heading chunk gets that heading's chunk_id as its parent_chunk_id.
        This seeds the parent-document retrieval self-FK without a second DB round-trip.
        """
        current_heading_id: Optional[str] = None
        for chunk in doc_chunks:
            if chunk.chunk_type == "heading":
                current_heading_id = chunk.chunk_id
            elif chunk.chunk_type in ("prose", "list", "citation_block"):
                if current_heading_id:
                    chunk.parent_chunk_id = current_heading_id
        return doc_chunks


# ——— TOC extraction helper (called from upload_tasks after load_document) ————


# ——— Process-wide Singleton ———————————————————————————————————————————————————
#
# Docling's converters carry the layout model (and, on the OCR path, Tesseract
# plumbing) — hundreds of MB of resident weights each. Constructing a loader per
# document meant every concurrent ingest loaded its own copy: six simultaneous
# uploads produced six "Loading weights: 0/770" bars and >4GB RSS, which is what
# was OOM-killing the Render worker on repeat.
#
# There is no reason for more than one per process. Always go through
# get_docling_loader() rather than instantiating DoclingPDFLoader directly.

_LOADER_SINGLETON: Optional["DoclingPDFLoader"] = None
_SINGLETON_LOCK = threading.Lock()


def get_docling_loader(max_tokens: int = 512, merge_peers: bool = True) -> "DoclingPDFLoader":
    """
    Return the shared process-wide DoclingPDFLoader, creating it on first use.

    Thread-safe: the worker runs `-P threads`, so concurrent documents race here.
    Construction is cheap (models load lazily on first convert); the important
    part is that everyone ends up with the SAME instance.
    """
    global _LOADER_SINGLETON

    if _LOADER_SINGLETON is not None:
        return _LOADER_SINGLETON

    with _SINGLETON_LOCK:
        if _LOADER_SINGLETON is None:
            _LOADER_SINGLETON = DoclingPDFLoader(
                max_tokens=max_tokens, merge_peers=merge_peers
            )
            logger.info("🦆 Created shared DoclingPDFLoader singleton")
    return _LOADER_SINGLETON


def extract_toc_from_docling_doc(doc) -> list:
    """
    Build a lightweight TOC list from a converted DoclingDocument.
    Returns a list of {"text": ..., "level": ..., "page": ...} dicts
    suitable for storing in document_sources.toc (JSONB).
    """
    toc = []
    try:
        from docling.datamodel.base_models import DocItemLabel
        for item in doc.texts:
            if str(getattr(item, "label", "")).lower().startswith("heading"):
                level_str = str(getattr(item, "label", "")).lower()
                # Map 'heading_1' → 1, 'heading_2' → 2, etc.
                try:
                    level = int(level_str.split("_")[-1])
                except (ValueError, IndexError):
                    level = 1
                page = None
                prov = getattr(item, "prov", None)
                if prov:
                    first = prov[0] if isinstance(prov, (list, tuple)) else prov
                    page = getattr(first, "page_no", None)
                toc.append({
                    "text": getattr(item, "text", ""),
                    "level": level,
                    "page": page,
                })
    except Exception as e:
        logger.debug(f"TOC extraction failed: {e}")
    return toc
